import type { KnowledgeEntry } from "@/lib/assistant-batimum/knowledge/types";
import {
  ACK_REPLY,
  CANCEL_NO_PENDING_REPLY,
  CONFIRM_NO_PENDING_REPLY,
  GREETING_REPLY,
  OFF_TOPIC_REPLY,
  READY_REPLY,
  SMALL_TALK_REPLY,
  THANKS_REPLY,
} from "@/lib/assistant-batimum/conversation";

export const CONVERSATION_KNOWLEDGE: KnowledgeEntry[] = [
  {
    id: "greeting",
    domain: "conversation",
    actionType: "answer",
    priority: 200,
    confidence: 0.98,
    patterns: [/^(?:bonjour|salut|hello|coucou|bonsoir|hey|allo)\b/],
    keywords: ["bonjour", "salut", "bonsoir", "hello", "coucou", "allo"],
    answer: () => ({ text: GREETING_REPLY }),
  },
  {
    id: "ready",
    domain: "conversation",
    actionType: "answer",
    priority: 205,
    confidence: 0.97,
    patterns: [
      /\b(?:t['']?es\s+pret|tu\s+es\s+pret)\b/,
      /\bpret\s+a\s+travaill/,
      /\betes[- ]vous\s+pret\b/,
      /^pret\s*[!?.]*$/,
    ],
    keywords: [
      "t es pret",
      "tu es pret",
      "pret a travailler",
      "etes vous pret",
      "pret",
    ],
    answer: () => ({ text: READY_REPLY }),
  },
  {
    id: "thanks",
    domain: "conversation",
    actionType: "answer",
    priority: 200,
    confidence: 0.98,
    patterns: [/^(?:merci|thanks|remercie|bcp|merci beaucoup)/],
    keywords: ["merci", "thanks", "remercie"],
    answer: () => ({ text: THANKS_REPLY }),
  },
  {
    id: "small_talk",
    domain: "conversation",
    actionType: "answer",
    priority: 200,
    confidence: 0.98,
    patterns: [/^(?:ca va|comment ca va|comment allez|tu vas bien)\s*\??$/],
    keywords: ["ca va", "comment allez-vous", "tu vas bien"],
    answer: () => ({ text: SMALL_TALK_REPLY }),
  },
  {
    id: "ack",
    domain: "conversation",
    actionType: "answer",
    priority: 190,
    confidence: 0.9,
    patterns: [/^(?:ok|parfait|nickel|super|compris|tres bien|d'accord)\s*[!?.]*$/],
    keywords: ["ok", "parfait", "nickel", "d'accord"],
    answer: () => ({ text: ACK_REPLY }),
  },
  {
    id: "farewell",
    domain: "conversation",
    actionType: "answer",
    priority: 195,
    confidence: 0.95,
    patterns: [
      /^(?:bonne journee|bonne journée|bonne soiree|bonne soirée|a bientot|à bientôt|a demain|à demain|au revoir)\b/,
    ],
    keywords: ["bonne journée", "à bientôt", "au revoir"],
    answer: () => ({ text: "À bientôt ! Je reste disponible pour piloter Batimum." }),
  },
  {
    id: "help_capabilities",
    domain: "conversation",
    actionType: "answer",
    priority: 85,
    confidence: 0.88,
    patterns: [/aide\b/, /que peux[- ]tu/, /comment utiliser/, /que sais[- ]tu/],
    keywords: ["aide", "que peux-tu faire", "comment utiliser"],
    answer: () => ({
      text: "Je peux répondre sur vos chiffres, clients, devis, factures, chantiers, planning et pilotage. Je peux aussi préparer des actions après votre confirmation.",
    }),
  },
  {
    id: "out_of_scope",
    domain: "conversation",
    actionType: "refuse",
    priority: 180,
    confidence: 0.95,
    patterns: [
      /\b(blague|raconte une histoire)\b/,
      /\b(politique|election|president)\b/,
      /\b(medecin|maladie)\b/,
      /\b(recette|gateau)\b/,
      /\b(devoirs?|dissertation)\b/,
      /\b(film|netflix|football|psg)\b/,
    ],
    keywords: ["blague", "politique", "medecin", "devoirs"],
    answer: () => ({ text: OFF_TOPIC_REPLY }),
  },
];

export const CONTEXT_SIGNALS = {
  confirmNoPending: CONFIRM_NO_PENDING_REPLY,
  cancelNoPending: CANCEL_NO_PENDING_REPLY,
};
