/**
 * Formulations utilisateur par intention — enrichit les keywords du matcher.
 * Objectif : couvrir des centaines de variantes naturelles sans dupliquer la logique métier.
 */
export const FORMULATION_KEYWORDS: Record<string, string[]> = {
  greeting: [
    "bonjour",
    "salut",
    "bonsoir",
    "hello",
    "coucou",
    "allo",
    "hey",
    "bjr",
    "bonjour batimum",
    "salut batimum",
  ],
  ready: [
    "t es pret",
    "tu es pret",
    "etes vous pret",
    "pret a travailler",
    "pret a bosser",
    "on commence",
    "on demarre",
    "tu es la",
    "pret",
  ],
  thanks: [
    "merci",
    "merci beaucoup",
    "thanks",
    "remercie",
    "bcp",
    "grand merci",
    "c est gentil",
  ],
  ack: ["ok", "parfait", "nickel", "super", "compris", "tres bien", "d accord"],
  count_clients: [
    "combien de clients",
    "nombre de clients",
    "combien client",
    "j ai combien de client",
    "j ai combien de clients",
    "total clients",
    "nb clients",
    "combien j ai de clients",
    "nombre client",
    "stats clients",
  ],
  create_client: [
    "cree un client",
    "creer client",
    "nouveau client",
    "ajoute client",
    "ajoute un client",
    "je veux creer un client",
    "j aimerais ajouter un client",
    "peux tu creer un client",
    "tu peux ajouter un client",
    "cree un client qui s appelle",
    "nouveau client au nom de",
    "ajoute l entreprise",
    "cree monsieur",
    "cree madame",
    "ajouter client",
    "inscrire client",
    "enregistrer client",
    "fiche client",
    "nouvelle fiche client",
  ],
  create_devis: [
    "cree un devis",
    "creer devis",
    "nouveau devis",
    "faire un devis",
    "preparer un devis",
    "devis pour",
    "chiffrer",
    "estimation",
    "proposition commerciale",
    "devis salle de bain",
    "devis cuisine",
    "devis renovation",
    "devis travaux",
    "monte un devis",
    "prepare un devis",
  ],
  count_devis: [
    "combien de devis",
    "nombre de devis",
    "total devis",
    "nb devis",
    "combien j ai de devis",
    "stats devis",
  ],
  show_quotes_to_follow_up: [
    "devis a relancer",
    "relancer devis",
    "devis en attente",
    "devis sans reponse",
    "quels devis relancer",
    "devis a suivre",
    "devis bloques",
    "devis en cours",
  ],
  monthly_revenue: [
    "ca du mois",
    "chiffre d affaires du mois",
    "combien j ai encaisse",
    "ca encaisse",
    "revenu du mois",
    "encaissements du mois",
    "combien encaisse",
    "ca mensuel",
  ],
  monthly_profit: [
    "benefice du mois",
    "combien ai je gagne ce mois",
    "marge du mois",
    "profit du mois",
    "gain du mois",
    "resultat du mois",
    "combien gagne ce mois",
  ],
  show_late_chantiers: [
    "chantiers en retard",
    "chantier en retard",
    "retard chantier",
    "chantiers depasses",
    "chantier qui depasse",
  ],
  show_unpaid_invoices: [
    "factures impayees",
    "factures non payees",
    "impayes",
    "factures en attente",
    "factures a encaisser",
    "qui me doit",
  ],
  create_rendez_vous: [
    "cree rdv",
    "creer rendez vous",
    "ajoute rdv",
    "nouveau rdv",
    "planifier rdv",
    "prendre rdv",
    "ajouter rendez vous",
    "fixer rdv",
  ],
  best_chantier_type: [
    "type chantier rentable",
    "chantier le plus rentable",
    "se porte le mieux",
    "marche le mieux",
    "meilleur sur quoi",
    "ou je gagne le plus",
    "gagne le plus",
    "type le plus rentable",
    "sur quoi je performe",
  ],
  btp_question: [
    "question btp",
    "norme btp",
    "dtu",
    "tva travaux",
    "debourse",
    "marge chantier",
    "prix au m2",
    "tarif horaire",
  ],
  cancellation: ["annule", "annuler", "stop", "laisse tomber", "oublie"],
  confirmation: ["oui", "confirme", "valide", "vas y", "c est bon", "go"],
  out_of_scope: [
    "blague",
    "raconte une blague",
    "raconte une histoire",
    "devoirs",
    "politique",
    "meteo",
  ],
  create_employe: [
    "cree employe",
    "creer salarie",
    "nouvel employe",
    "ajoute employe",
    "nouveau salarie",
    "ajouter salarie",
    "embaucher",
    "recruter",
  ],
  count_factures: [
    "combien de factures",
    "nombre factures",
    "total factures",
    "nb factures",
  ],
  count_chantiers: [
    "combien de chantiers",
    "nombre chantiers",
    "chantiers en cours",
    "total chantiers",
  ],
  company_advice: [
    "analyse mon activite",
    "mes points faibles",
    "conseil activite",
    "que faire",
    "priorites",
    "analyse entreprise",
  ],
};

const CREATE_VERBS = [
  "cree",
  "creer",
  "ajoute",
  "ajouter",
  "nouveau",
  "nouvelle",
  "fais",
  "faire",
  "prepare",
  "preparer",
  "monte",
  "monter",
  "lance",
  "lancer",
  "je veux",
  "j aimerais",
  "peux tu",
  "tu peux",
];

const COUNT_PREFIXES = [
  "combien de",
  "combien j ai de",
  "nombre de",
  "nb de",
  "total",
  "stats",
  "donne moi le nombre de",
];

function expandCount(entity: string): string[] {
  return COUNT_PREFIXES.map((p) => `${p} ${entity}`);
}

/** Enrichit les formulations avec des combinaisons générées. */
const GENERATED: Record<string, string[]> = {
  create_client: CREATE_VERBS.flatMap((v) => [
    `${v} client`,
    `${v} un client`,
    `${v} nouveau client`,
    `${v} une fiche client`,
  ]),
  create_devis: CREATE_VERBS.flatMap((v) => [
    `${v} devis`,
    `${v} un devis`,
    `${v} nouveau devis`,
    `${v} devis salle de bain`,
    `${v} devis cuisine`,
    `${v} devis renovation`,
  ]),
  count_clients: expandCount("clients").concat(expandCount("client")),
  count_devis: expandCount("devis"),
  count_factures: expandCount("factures"),
  count_chantiers: expandCount("chantiers"),
  show_unpaid_invoices: [
    "factures impayees",
    "impayes",
    "qui me doit",
    "factures non reglees",
    "factures en attente de paiement",
    "relancer factures",
    "factures a encaisser",
  ].flatMap((p) => [`montre ${p}`, `liste ${p}`, p]),
  monthly_revenue: [
    "ca du mois",
    "chiffre affaires mois",
    "encaissements",
    "revenus mensuels",
  ].flatMap((p) => [`quel est mon ${p}`, p, `combien ${p}`]),
  best_chantier_type: [
    "type chantier rentable",
    "meilleur type chantier",
    "sur quoi je performe",
    "chantier le plus rentable",
  ].flatMap((p) => [p, `quel ${p}`, `mon ${p}`]),
  create_rendez_vous: CREATE_VERBS.flatMap((v) => [
    `${v} rdv`,
    `${v} rendez vous`,
    `${v} un rdv`,
    `${v} rendez-vous`,
  ]),
  create_employe: CREATE_VERBS.flatMap((v) => [
    `${v} employe`,
    `${v} salarie`,
    `${v} un employe`,
    `${v} un salarie`,
  ]),
  btp_question: [
    "tva travaux",
    "debourse horaire",
    "marge chantier",
    "prix au m2",
    "tarif pose",
    "norme dtu",
    "question technique",
  ].flatMap((p) => [p, `quelle ${p}`, `c est quoi ${p}`]),
};

GENERATED.greeting = [
  ...(FORMULATION_KEYWORDS.greeting ?? []),
  "bonjour a tous",
  "bonjour l equipe",
  "salut l assistant",
  "hello batimum",
  "coucou batimum",
  "bonjour monsieur",
  "bonjour madame",
  "rebonjour",
  "re bonjour",
];

for (const [id, extra] of Object.entries(GENERATED)) {
  FORMULATION_KEYWORDS[id] = [...new Set([...(FORMULATION_KEYWORDS[id] ?? []), ...extra])];
}

export function countFormulations(): number {
  return Object.values(FORMULATION_KEYWORDS).reduce((n, arr) => n + arr.length, 0);
}
