/** Banques de synonymes pour génération de formulations naturelles. */

export const ACTION_VERBS = [
  "cree",
  "creer",
  "crée",
  "ajoute",
  "ajouter",
  "nouveau",
  "nouvelle",
  "nouvel",
  "prepare",
  "preparer",
  "fais",
  "faire",
  "lance",
  "lancer",
  "monte",
  "monter",
  "enregistre",
  "enregistrer",
  "inscris",
  "inscrire",
  "ouvre",
  "ouvrir",
  "affiche",
  "afficher",
  "montre",
  "montrer",
  "liste",
  "lister",
  "cherche",
  "chercher",
  "trouve",
  "trouver",
  "recherche",
  "rechercher",
  "modifie",
  "modifier",
  "supprime",
  "supprimer",
  "annule",
  "annuler",
  "relance",
  "relancer",
  "planifie",
  "planifier",
  "deplace",
  "deplacer",
  "filtre",
  "filtrer",
  "analyse",
  "analyser",
  "compare",
  "comparer",
];

export const POLITE_PREFIXES = [
  "",
  "je veux ",
  "j aimerais ",
  "je voudrais ",
  "peux tu ",
  "tu peux ",
  "est ce que tu peux ",
  "on peut ",
  "on va ",
  "j ai besoin de ",
];

export const COUNT_PREFIXES = [
  "combien de ",
  "combien j ai de ",
  "combien ai je de ",
  "nombre de ",
  "nb de ",
  "total ",
  "stats ",
  "donne moi le nombre de ",
  "j ai combien de ",
  "on a combien de ",
  "je possede combien de ",
];

export const LIST_PREFIXES = [
  "liste ",
  "liste mes ",
  "liste les ",
  "montre ",
  "montre mes ",
  "montre les ",
  "affiche ",
  "affiche mes ",
  "affiche les ",
  "quels sont mes ",
  "quelles sont mes ",
  "quels ",
  "quelles ",
];

export const RENTABILITY_SYNONYMS = [
  "rentabilite",
  "rentable",
  "marge",
  "ca rapporte",
  "gagne",
  "gagne le plus",
  "plus rentable",
  "plus interessant",
  "plus profitable",
  "plus remunerateur",
  "meilleur",
  "performant",
  "se porte le mieux",
  "marche le mieux",
];

export const ENTITY_LABELS: Record<string, string[]> = {
  clients: ["client", "clients", "fiche client", "portefeuille client", "portefeuille clients"],
  devis: ["devis", "estimation", "proposition", "propositions", "offre", "offres"],
  factures: ["facture", "factures", "facturation", "encaissement", "encaissements"],
  chantiers: ["chantier", "chantiers", "travaux", "chantier en cours"],
  employes: ["employe", "employes", "salarie", "salaries", "ouvrier", "ouvriers", "equipe"],
  fournitures: ["fourniture", "fournitures", "materiel", "materiaux", "stock"],
  commandes: ["commande", "commandes", "bon de commande"],
  planning: ["planning", "rdv", "rendez vous", "rendez-vous", "agenda", "calendrier"],
  pilotage: ["pilotage", "rentabilite", "marge", "benefice", "ca", "chiffre d affaires"],
};

export const BTP_TRADES = [
  "plomberie",
  "plombier",
  "placo",
  "plaquiste",
  "carrelage",
  "carreleur",
  "faience",
  "faïence",
  "peinture",
  "peintre",
  "electricite",
  "électricité",
  "electricien",
  "menuiserie",
  "menuisier",
  "maconnerie",
  "maçonnerie",
  "macon",
  "toiture",
  "couvreur",
  "isolation",
  "isoler",
  "chauffage",
  "climatisation",
  "salle de bain",
  "sdb",
  "wc",
  "cuisine",
  "renovation",
  "rénovation",
  "neuf",
  "construction",
  "sav",
  "depannage",
  "dépannage",
  "etancheite",
  "étanchéité",
  "terrasse",
  "facade",
  "façade",
  "ravalement",
];

export const CONVERSATION_PHRASES = [
  "bonjour",
  "salut",
  "bonsoir",
  "allo",
  "hello",
  "coucou",
  "ca va",
  "comment ca va",
  "comment allez vous",
  "merci",
  "merci beaucoup",
  "ok",
  "parfait",
  "nickel",
  "super",
  "genial",
  "génial",
  "bonne journee",
  "bonne journée",
  "a demain",
  "à demain",
  "au revoir",
  "t es pret",
  "tu es pret",
  "pret a travailler",
];
